# Generated by Django 4.2.7 on 2026-03-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioproducto',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('STOCK', 'Ajuste de stock'), ('DESTACAR', 'Destacar producto'), ('Q_DESTACAR', 'Quitar destacado'), ('PUBLICAR', 'Publicar producto'), ('Q_PUBLICAR', 'Quitar publicacion')], max_length=20),
        ),
    ]
