# Generated by Django 4.2.7 on 2026-03-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('detalle', models.CharField(max_length=220)),
                ('stock_unidad', models.PositiveIntegerField(default=0)),
                ('unidades_por_caja', models.PositiveIntegerField(default=1)),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_caja_bs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
