# Generated by Django 4.2.7 on 2026-03-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
