# Generated by Django 5.1.1 on 2026-05-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_caja_bs',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, help_text='Ej: Negro, Blanco, Rojo (separados por coma)', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_tipo',
            field=models.CharField(choices=[('PORCENTAJE', '%'), ('MONTO', 'Bs')], default='PORCENTAJE', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor del descuento', max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio con descuento (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, help_text='Ej: S, M, L, XL (separados por coma)', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio normal', max_digits=10),
        ),
    ]
