# Generated by Django 5.1.1 on 2026-05-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_precio_caja_bs_producto_colores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sexo',
            field=models.CharField(choices=[('UNISEX', 'Unisex'), ('MUJER', 'Mujer'), ('HOMBRE', 'Hombre')], default='UNISEX', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
    ]
