# Generated by GitHub Copilot on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_sexo_productoimagen'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "\n"
                "ALTER TABLE productos_producto\n"
                "    ADD COLUMN IF NOT EXISTS tallas varchar(100) NOT NULL DEFAULT '',\n"
                "    ADD COLUMN IF NOT EXISTS colores varchar(100) NOT NULL DEFAULT '';\n"
            ),
            reverse_sql=(
                "\n"
                "ALTER TABLE productos_producto\n"
                "    DROP COLUMN IF EXISTS tallas,\n"
                "    DROP COLUMN IF EXISTS colores;\n"
            ),
        ),
    ]
