services:
  - type: web
    name: sistema-textil
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn sistema_textil.wsgi:application
