"""
Django settings for sistema_textil project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
from urllib.parse import urlparse, unquote

from decouple import config, Csv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_or_config(name, default=''):
    """Prefer real OS environment (Render/Heroku) so secrets are never shadowed by an empty .env."""
    if name in os.environ:
        return (os.environ.get(name) or '').strip()
    return (str(config(name, default=default) or '')).strip()


def _cloudinary_storage_settings():
    """
    Credentials for django-cloudinary-storage / cloudinary.config.
    Supports CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME + API_KEY + API_SECRET.
    """
    url = _env_or_config('CLOUDINARY_URL')
    if url:
        parsed = urlparse(url)
        if parsed.scheme != 'cloudinary':
            raise ImproperlyConfigured(
                'CLOUDINARY_URL debe comenzar con cloudinary:// (p. ej. cloudinary://KEY:SECRET@CLOUD_NAME).'
            )
        return {
            'CLOUD_NAME': (parsed.hostname or '').strip(),
            'API_KEY': unquote(parsed.username or ''),
            'API_SECRET': unquote(parsed.password or ''),
        }
    # CLOUDINARY_API_SECRE: typo frecuente en el dashboard de Render (falta la T final).
    api_secret = _env_or_config('CLOUDINARY_API_SECRET') or _env_or_config('CLOUDINARY_API_SECRE')
    return {
        'CLOUD_NAME': _env_or_config('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': _env_or_config('CLOUDINARY_API_KEY'),
        'API_SECRET': api_secret,
    }

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-15(4^2d42%w=4qmro8g(z-p@5taqk=6t7m60ynzxw%l_3y+p++')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        f'https://{host}' for host in ALLOWED_HOSTS if host and host != '*'
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'apps.core.apps.CoreConfig',
    'apps.productos.apps.ProductosConfig',
    'apps.categorias.apps.CategoriasConfig',
    'apps.destacados.apps.DestacadosConfig',
    'apps.stock.apps.StockConfig',
    'apps.estadisticas.apps.EstadisticasConfig',
    'apps.historial.apps.HistorialConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

try:
    import whitenoise  # noqa: F401  # pyright: ignore[reportMissingImports]
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    _STATICFILES_BACKEND = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
except ModuleNotFoundError:
    _STATICFILES_BACKEND = 'django.contrib.staticfiles.storage.StaticFilesStorage'

ROOT_URLCONF = 'sistema_textil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_textil.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-bo'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True

# Configuración para almacenamiento persistente en Render
is_render = (
    os.environ.get('RENDER') == 'true' or 
    os.environ.get('RENDER_SERVICE_ID') is not None or
    'RENDER' in os.environ
)

# Configuración de Cloudinary (OS env primero; evita api_secret vacío por .env local)
CLOUDINARY_STORAGE = _cloudinary_storage_settings()

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = _STATICFILES_BACKEND

# Configuración de Media URL y Storage
MEDIA_URL = '/media/'

# Cloudinary solo con las tres credenciales (nombre, key, secret). Así el build en Render no
# revienta si CLOUDINARY_CLOUD_NAME existe pero los secretos solo están en runtime, o si faltan vars.
_use_cloudinary = bool(
    CLOUDINARY_STORAGE['CLOUD_NAME']
    and CLOUDINARY_STORAGE['API_KEY']
    and CLOUDINARY_STORAGE['API_SECRET']
)
if CLOUDINARY_STORAGE['CLOUD_NAME'] and not _use_cloudinary:
    warnings.warn(
        'Cloudinary incompleto: hay nombre de nube pero faltan CLOUDINARY_API_KEY / '
        'CLOUDINARY_API_SECRET (o CLOUDINARY_URL con key y secret). Se usa almacenamiento '
        'local de media hasta que estén las tres credenciales.',
        UserWarning,
        stacklevel=1,
    )

if _use_cloudinary:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': _STATICFILES_BACKEND,
        },
    }
    MEDIA_ROOT = ''
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': _STATICFILES_BACKEND,
        },
    }
    if is_render:
        MEDIA_ROOT = '/opt/render/project/src/media'
    else:
        MEDIA_ROOT = BASE_DIR / 'media'

if _use_cloudinary:
    import cloudinary

    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
        api_key=CLOUDINARY_STORAGE['API_KEY'],
        api_secret=CLOUDINARY_STORAGE['API_SECRET'],
        secure=True,
    )

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/productos/'
LOGOUT_REDIRECT_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
